_BASE_: ../Base-SBS.yml

MODEL:
  BACKBONE:
    WITH_IBN: False
    NAME: build_osnet_backbone
    DEPTH: x1_0
    FEAT_DIM: 512
    PRETRAIN: True
  HEADS:
    POOL_LAYER: GlobalMaxPool   # required for onnx-tensorrt inference

KD:
  EMA:
    ENABLED: True

INPUT:
  AUTOAUG:
    ENABLED: True
    PROB: 0.4

SOLVER:
  OPT: Adam
  MAX_EPOCH: 200
  IMS_PER_BATCH: 64

DATASETS:
  NAMES: ('Pharmacity',)
  TESTS: ("Pharmacity",)

OUTPUT_DIR: logs/PMC/sbs_osnet_PMC
